<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddl_Commune</name>
   <tag></tag>
   <elementGuidId>2d03081e-5381-4ce2-b95d-72dbdac67fed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[1]/div/div[3]/div/div[2]/div/div/section[1]/section/ul/div/div[2]/div[2]/div/div/section/form/div[9]/div/div/div[1]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
